package com.campusnova.service;
import com.campusnova.dto.ChatRequest; import com.campusnova.knowledge.*; import com.campusnova.repository.ChatHistoryRepository; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import java.util.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class NovaChatServiceTest { @Mock ConversationService conversation; @Mock KnowledgeRetrievalService retrieval; @Mock CollegeRelevanceService relevance; @Mock BedrockService bedrock; @Mock GroundingValidationService grounding; @Mock ChatHistoryRepository history; @InjectMocks NovaChatService nova;
 private ChatRequest request(String q){ChatRequest r=new ChatRequest();r.setQuestion(q);r.setSessionId("test-session");return r;} private RetrievalResult result(double score){return new RetrievalResult(Collections.singletonList(new KnowledgeDocument("FAQ: Library hours","Library","What are library timings?\nThe demo library closes at 7 PM.",false)),score);}
 @Test void exactFaqReturnsDirectVerifiedAnswer(){when(conversation.recentTerms(anyString())).thenReturn(Collections.<String>emptyList());when(retrieval.retrieve(anyString(),anyCollection())).thenReturn(result(.9));when(relevance.isCollegeRelated(anyString(),any(RetrievalResult.class),anyCollection())).thenReturn(true);Map<String,Object> answer=nova.respond(request("What are library timings?"));assertEquals("DIRECT_FAQ",answer.get("responseType"));assertEquals(Boolean.TRUE,answer.get("answered"));verify(bedrock,never()).generate(anyString(),any(RetrievalResult.class));}
 @Test void rephrasedQuestionCanUseGroundedAiResponse(){when(conversation.recentTerms(anyString())).thenReturn(Collections.<String>emptyList());when(retrieval.retrieve(anyString(),anyCollection())).thenReturn(result(.3));when(relevance.isCollegeRelated(anyString(),any(RetrievalResult.class),anyCollection())).thenReturn(true);when(bedrock.generate(anyString(),any(RetrievalResult.class))).thenReturn(Optional.of("The library closes at 7 PM."));when(grounding.acceptable(anyString(),any(RetrievalResult.class))).thenReturn(true);assertEquals("AI_RAG",nova.respond(request("When can I use the library?")).get("responseType"));}
 @Test void unavailableCollegeQuestionBecomesKnowledgeGap(){when(conversation.recentTerms(anyString())).thenReturn(Collections.<String>emptyList());when(retrieval.retrieve(anyString(),anyCollection())).thenReturn(new RetrievalResult(Collections.<KnowledgeDocument>emptyList(),0));when(relevance.isCollegeRelated(anyString(),any(RetrievalResult.class),anyCollection())).thenReturn(true);Map<String,Object> answer=nova.respond(request("What is the ID card replacement procedure?"));assertEquals("KNOWLEDGE_GAP",answer.get("responseType"));assertTrue(answer.get("answer").toString().contains("not currently available"));}
 @Test void unrelatedQuestionStaysWithinCollegeScope(){when(conversation.recentTerms(anyString())).thenReturn(Collections.<String>emptyList());when(retrieval.retrieve(anyString(),anyCollection())).thenReturn(new RetrievalResult(Collections.<KnowledgeDocument>emptyList(),0));when(relevance.isCollegeRelated(anyString(),any(RetrievalResult.class),anyCollection())).thenReturn(false);assertEquals("OUT_OF_DOMAIN",nova.respond(request("Give me a cooking recipe")).get("responseType"));}
 @Test void bedrockFailureFallsBackToRetrievedKnowledge(){when(conversation.recentTerms(anyString())).thenReturn(Collections.singletonList("library timings"));when(retrieval.retrieve(anyString(),anyCollection())).thenReturn(result(.25));when(relevance.isCollegeRelated(anyString(),any(RetrievalResult.class),anyCollection())).thenReturn(true);when(bedrock.generate(anyString(),any(RetrievalResult.class))).thenReturn(Optional.<String>empty());Map<String,Object> answer=nova.respond(request("Is it open on Saturday?"));assertEquals("RETRIEVAL_FALLBACK",answer.get("responseType"));verify(history).save(any());}
}
